name: flutter_gcs
description: A mobile GCS using Flutter and USB OTG
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:

  flutter_test:
    sdk: flutter

  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6

  # USB serial port support (for SiK via OTG)
  flutter_serial: ^0.0.3

  # State management
  flutter_riverpod: ^2.5.1

  # Google Maps for drone tracking
  google_maps_flutter: ^2.6.0

  # LatLng utility
  latlong2: ^0.9.0

  # (Optional) Logging for debugging
  logger: ^2.0.2

  # (Optional) Future MAVLink Dart FFI
  ffi: ^2.1.0

flutter: 
  assets:
    - assets/icons/
